### ISSUE TITLE
Arabic Events Considerations

### ISSUE THREAD

**Issue by tannerj028** [NightMachinery/jalali-calendar-cli#4]
Hi and tnx for the proj. As far as I know Arabic calendar is not in sync with our Jalali one.  Thus, if in this year, today's an Arabic holiday then in next year it is sometime before I guess. Is that considered in this repo?

**Comment by NightMachinery** [comment]
The readme explains this, but in short, see https://github.com/NightMachinery/jalali-calendar-cli/blob/master/jalali_calendar_cli/holidays.json .
